# 配置文件加密key
jasypt:
  encryptor:
    password: xboot

server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb

xboot:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认JWT 启用Redis后设置为true后，token将存入redis，并具有单点登录功能
    redis: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 七牛云配置
  qiniu:
    accessKey: 你的accessKey
    secretKey: 你的secretKey
    bucket: 你的空间名
    domain: 你的测试域名，如http://p77xsahe9.bkt.clouddn.com
    # 存储区域 -1自动判断 0华东 1华北 2华南 3北美 4东南亚
    zone: -1
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 你的appKey

# 忽略鉴权url
ignored:
  urls:
    - /xboot/user/regist
    - /xboot/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

# Swagger界面内容配置
swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.exrick.xboot.*.*.entity
  typeEnumsPackage: cn.exrick.xboot.*.*.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    #capital-mode: true
    # 逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 日志
logging:
  file: xboot-logs/xboot.log
