# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: xboot

server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    # 最大吞吐量不限制
    max-swallow-size: -1
  # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  shutdown: graceful

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
    password: ENC(uOtmALFgsfxgYzEg1uLXl3O/tg6X1Dy25I3SdAeqqETOyZbDwmaW0/EZEusIh6hK)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(uOtmALFgsfxgYzEg1uLXl3O/tg6X1Dy25I3SdAeqqETOyZbDwmaW0/EZEusIh6hK)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 防SQL注入过滤
        wall:
          config:
            # 允许多条sql同时执行
            multi-statement-allow: true
  jpa:
    show-sql: true
    # 自动生成表结构
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  # Elasticsearch
  data:
    elasticsearch:
      # 未使用到ES 关闭其持久化存储
      repositories:
        enabled: false
  elasticsearch:
    rest:
      # 要连接的ES客户端Rest Uri 多个逗号分隔
      uris: http://localhost:9200
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc
    jdbc:
      # 自动生成表 若已有表数据请务必关闭 ALWAYS/EMBEDDED/NEVER
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            # 允许调度程序节点一次获取（触发）的最大触发器数
            batchTriggerAcquisitionMaxCount: 5
          jobStore:
            # 加锁调度
            acquireTriggersWithinLock: true
            # “容忍”触发器经过下一次触发时间的毫秒数
            misfireThreshold: 10000
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  boot:
    admin:
      # 修改上下文路径
      context-path: /xboot/admin
      client:
        # 服务端url
        url: http://127.0.0.1:${server.port}/xboot/admin
        instance:
          # 实例url
          service-base-url: http://127.0.0.1:${server.port}/

xboot:
  # 全局限流
  ratelimit:
    # 开启
    enable: true
    # 每1秒内（单位毫秒）
    timeout: 1000
    # 总限制200个请求（单位个）
    limit: 200
  # IP限流
  iplimit:
    # 开启
    enable: true
    # 每1秒内（单位毫秒）
    timeout: 1000
    # 每个ip限制20个请求（单位个）
    limit: 20
  # token交互方式
  token:
    # 默认为true，token将存入redis，并具有单设备登录、自动刷新token过期时间功能 设为false使用JWT交互
    redis: true
    # 是否开启单设备登陆 一个账号仅支持同时一台设备登录 仅当token交互方式为redis时生效
    sdl: false
    # token中存储用户权限数据 开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间 redis模式有请求自动刷新过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择 保存登录状态/记住我 对应token过期时间 不会自动刷新过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  # 使用Spring @Cacheable注解失效时间
  cache:
    # 缓存过期时间 Duration类型 D–天 H小时 M–分钟 S–秒 永久不过期设为非正值
    timeToLive: 15D
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 文件大小上传配置 单位MB
  maxUploadFile: 5
  # 七牛云配置
  qiniu:
    accessKey: 你的accessKey
    secretKey: 你的secretKey
    bucket: 你的空间名
    domain: 你的域名，如http://p77xsahe9.bkt.clouddn.com
    # 存储区域 -1自动判断 0华东 1华北 2华南 3北美 4东南亚
    zone: -1
  # 腾讯位置服务key配置 腾讯位置服务官网注册添加key ip定位所需
  qqlbs:
    key: 你的腾讯位置服务key

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /xboot/login # 登录接口
    - /xboot/oauth2/authorize # 认证接口

# 忽略url
ignored:
  # 无需登录认证的请求
  urls:
    - /xboot/oauth2/**
    - /xboot/actuator/**
    - /xboot/admin/**
    - /xboot/dictData/getByType/**
    - /xboot/user/regist
    - /xboot/common/**
    - /druid/**
    - /doc.html
    - /swagger-resources/**
    - /v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /xboot/test/**
  # 限流及黑名单不拦截的路径
  limitUrls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

# Actuator
management:
  health:
    # 暂未用到ES 关闭其健康检查
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
  endpoints:
    web:
      base-path: /xboot/actuator/
      exposure:
        include: '*'

# 接口文档增强UI Swagger界面内容配置
knife4j:
  enable: true

swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://xboot.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com
  # 分组名
  group: 1.XBoot管理接口 v1.0

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
    # 日志控制台打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: xboot-logs
  logback:
    rollingpolicy:
      # 最大保存天数
      max-history: 7
      # 每个文件最大大小
      max-file-size: 5MB
